services:
  web:
    container_name: natalgf
    image: natalgf:latest
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - STORAGE_DIR=/data/natalgf/images
    volumes:
      - ./data/images:/data/natalgf/images
